### ISSUE TITLE
Error cannot find action with ajinx selenoid URI

### ISSUE THREAD

**Issue by hiqqs** [ajinx/selenoid#1]
I get this error
`An action could not be found at the URI 'https://api.github.com/repos/ajinx/selenoid/tarball/v2'`

when using basic configuration:

```
jobs:
  build:
    runs-on: ubuntu-latest
    name: lfg
    steps:
    - name: Start selenoid
      uses: ajinx/selenoid@v2
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn appStatus
```

**Comment by ajinx** [comment]
Can you try with following snippet

```
jobs:
  build:
    runs-on: ubuntu-latest
    name: lfg
    steps:
    - uses: actions/checkout@v2
    - name: Start selenoid
       uses: ajinx/selenoid@v2
    - run: yarn install --frozen-lockfile
    - name: Run tests
       env:
        SELENIUM_HUB_HOST: 'localhost'
       run: yarn appStatus
```

Let me know if it didn't worked out

Thanks,
Ajinkya

**Comment by hiqqs** [comment]
I get another error `every step must define a `uses` or `run` key` with the format you have above

I adjusted the format to below and it runs but still get the same error `An action could not be found at the URI 'https://api.github.com/repos/ajinx/selenoid/tarball/v2'`

```
jobs:
  build:
    runs-on: ubuntu-latest
    name: lfg
    steps:
    - uses: actions/checkout@v2
    - name: Start selenoid
      uses: ajinx/selenoid@v2
    - run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn appStatus
      env:
        SELENIUM_HUB_HOST: 'localhost'
```
